// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    LanguageMenu: typeof import('./components/LanguageMenu.vue')['default']
    PromotionTag: typeof import('./components/PromotionTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchingTag: typeof import('./components/SearchingTag.vue')['default']
    Sider: typeof import('./components/Sider.vue')['default']
    SiteSearchConfig: typeof import('./components/SiteSearchConfig.vue')['default']
    SiteStatus: typeof import('./components/SiteStatus.vue')['default']
    SiteSwitch: typeof import('./components/SiteSwitch.vue')['default']
  }
}
